# Generated by Django 3.1.2 on 2021-03-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('attempts', models.IntegerField(default=0)),
                ('locked', models.IntegerField(default=0)),
            ],
        ),
    ]
