# Generated by Django 3.1.2 on 2021-03-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transdate', models.DateField(auto_now_add=True)),
                ('cfname', models.CharField(max_length=100)),
                ('clname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('ccity', models.CharField(max_length=50)),
                ('ptype', models.CharField(max_length=100)),
                ('product', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpoc.login')),
            ],
        ),
    ]
