# Generated by Django 3.1.7 on 2021-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpoc', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ccity',
            field=models.CharField(choices=[('mumbai', 'MUMBAI'), ('delhi', 'DELHI'), ('banglore', 'BANGLORE'), ('dusseldore', 'DUSSELDORF'), ('berlin', 'BERLIN'), ('paris', 'PARIS'), ('moscow', 'MOSCOW'), ('kazan', 'KAZAN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('india', 'INDIA'), ('germany', 'GERMANY'), ('france', 'FRANCE'), ('russia', 'RUSSIA')], max_length=50),
        ),
    ]
