# Generated by Django 3.1.7 on 2021-03-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpoc', '0003_auto_20210305_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='nicknames',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
