# Generated by Django 3.1.7 on 2021-03-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpoc', '0004_login_nicknames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='nicknames',
        ),
    ]
