# Generated by Django 3.1.7 on 2021-03-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpoc', '0005_remove_login_nicknames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='transactionID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
