# Generated by Django 3.1.7 on 2021-03-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpoc', '0008_auto_20210306_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='transactionID',
            field=models.AutoField(default=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='customer_id',
            field=models.AutoField(default=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
